/*FUNCTION 생성*/
CREATE OR REPLACE FUNCTION FN_CODE_NM(V_CD VARCHAR2, V_CD2 VARCHAR2)
RETURN VARCHAR2  
IS V_NM VARCHAR2(100); 
BEGIN
	SELECT CD_NM1 INTO V_NM 
	  FROM TB_CD_MST
	 WHERE CD_VAL = V_CD
	   AND CD_VAL1 = V_CD2;
	   
	RETURN V_NM; 
END FN_CODE_NM;

--SELECT FN_CODE_NM('001','A') FROM DUAL;

-----------------------------------------------------
/*PROCEDURE 생성*/
CREATE OR REPLACE PROCEDURE MAN.PR_ITEM_MERGE(
	IV_ITEM_CD IN VARCHAR2,
	IV_ITEM_NM IN TB_ITEM.ITEM_NM%TYPE,
	OV_REG_DT OUT TB_ITEM.REG_DT%TYPE 
)
IS 
	V_CNT NUMBER;
	V_REG_DT DATE;
BEGIN
	SELECT COUNT(*) INTO V_CNT
	  FROM TB_ITEM 
	 WHERE ITEM_CD = IV_ITEM_CD;
	
	IF V_CNT = 0 THEN
		INSERT INTO TB_ITEM(ITEM_CD, ITEM_NM, REG_DT, UPD_DT)
		VALUES(IV_ITEM_CD, IV_ITEM_NM, SYSDATE, SYSDATE);
	ELSE
		UPDATE TB_ITEM 
		   SET ITEM_NM = IV_ITEM_NM
		   ,   UPD_DT = SYSDATE 
		  WHERE ITEM_CD = IV_ITEM_CD;
	END IF;

	SELECT REG_DT INTO V_REG_DT
	  FROM TB_ITEM 
	 WHERE ITEM_CD = IV_ITEM_CD;
	
	OV_REG_DT := V_REG_DT;
	COMMIT;
	EXCEPTION
		WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('예상치 못한 에러가 발생했습니다.');
		ROLLBACK;
	RETURN;
END PR_ITEM_MERGE;


DECLARE
	V_REG_DT DATE;
BEGIN
	PR_ITEM_MERGE('A0004','아이온익6',V_REG_DT);
	DBMS_OUTPUT.PUT_LINE('프로시저 결과 값' || V_REG_DT);
END;

